### ISSUE TITLE
Fix the contact page

### ISSUE THREAD

**Issue by shippy** [shippy/shippy.github.io#25]
- [ ] There should be a form action, or the form should be removed
- [x] There shouldn't be a royal plural (-> "Contact me")
- [x] There shouldn't be a phone column
- [x] Add title to Github link

**Comment by ubong-s** [comment]
This was part of the last milestone, that's why modifications weren't made yet

**Comment by ubong-s** [comment]
This  needs a discussion. Do you have any service in mind for the form submissions?

**Comment by shippy** [comment]
I take it this would require signing up with something like MailChimp?

**Comment by ubong-s** [comment]
Probably. There’s a free service I use most of the time… Free for 2000
emails monthly, Formspree(
https://formspree.io/). You can check it out

**Comment by shippy** [comment]
Let's try it - I registered and made a form with action to `https://formspree.io/f/mvgpzddj` (which I'm assuming is safe to share here, given that it will be readable in the source code).

**Comment by ubong-s** [comment]
Thanks. I'll incorporate it

**Comment by ubong-s** [comment]
Implementation made. I think your settings on formspree are a bit off. Did you tweak anything after creating the form?

**Comment by shippy** [comment]
I did - I think I set the required domain to simon.podhajsky.net.
